# Generated by Django 2.0 on 2021-05-05 09:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cyliner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('Business_Name', models.CharField(max_length=200)),
                ('person_Name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('Verified_status', models.CharField(max_length=200)),
                ('TimeStamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
