# Generated by Django 2.0 on 2021-05-05 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cylinderapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cyliner',
            new_name='cylinder',
        ),
        migrations.AlterModelOptions(
            name='cylinder',
            options={'verbose_name': 'cylinder', 'verbose_name_plural': 'cylinders'},
        ),
    ]
