# Generated by Django 2.0 on 2021-05-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cylinderapp', '0002_auto_20210505_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cylinder',
            options={'verbose_name': 'cylinder', 'verbose_name_plural': 'cylinder'},
        ),
        migrations.AlterField(
            model_name='cylinder',
            name='Verified_status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='cylinder',
            name='contact',
            field=models.BigIntegerField(),
        ),
    ]
